### ISSUE TITLE
Adding uncompiled typescript library

### ISSUE THREAD

**Issue by stefansandulescu** [rjerue/craco-babel-loader#4]
I have a "common library" written in Typescript and I want to use it in a couple more projects. I don't want to create a npm package from it, I just want to import it as "uncompiled package" which will be compiled in the same time as the app, but I'm having trouble setting this up.
I followed the example and added the following to the plugins section
```
plugins: [
      {
          plugin: rewireBabelLoader, 
          options: { 
            includes: [resolveApp("node_modules/common-library")],
            excludes: [/node_modules/]
          }
        }
    ]
```
I also added the following to the babel section in my `craco.config.js`
```
presets: [
  "@babel/preset-env",
  "@babel/preset-typescript",
  "@babel/preset-react",
],
plugins: [
  '@babel/plugin-transform-typescript',
  ...(whenProd(() => [
    [
      'babel-plugin-jsx-remove-data-test-id',
      {
        attributes: 'data-test'
      }
    ]
  ]) || []),
],
```
However, it doesn't work as I get the following error from the common-library:
`Module parse failed: The keyword 'interface' is reserved (5:0)`
Can I please get some guidance on this?
Thank you

**Comment by rjerue** [comment]
Typically the flow that I see for this is to have the code in your node_modules be javascript. Point of this library is to allow for things in your node modules that aren't transpiled to be so just as much as your react source code is.

That being said, I do use this in TypeScript codebases, though typically I have the TypeScript already compiled to JavaScript. Since TS can compile to es2015 without any issues, I am unsure as to why you'd need this. There's tools like TSDX that'll even bundle it really nicely.

The order at which babel runs things is important. This library adds only effects the the directories that transforms are run, not their order. I'd suggest seeing if you can run that transform earlier.

A working config from an ejected CRA could also demonstrate the what settings that work look like vs. a config that this + craco will output.

**Comment by stefansandulescu** [comment]
Thank you for your response, I made it work by overriding webpack config like this (since cra's config only takes into account the `appSrc` folder):
```
webpackConfig.module.rules[3].oneOf[1].include = [
  resolveApp('node_modules/common-library'),
  resolveApp('src'),
];
```
I hope it helps someone.
